[project]
name = "Sotsuken"
version = "0.1.0"

requires-python = ">=3.10,<3.12"

dependencies = [
    "cupy-cuda12x==12.3.0",
    "numpy",
    "opencv-python",
    "mss",
]

[tool.uv]
no-build-isolation = true
